name: Build and test
on:
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      msSql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.TEST_DATABASE_INSTANCE_PASSWORD }}
    env:
      EILEEN_TESTS_CONNECTION_STRING: 'Data Source=.;User ID=sa;Password=${{ secrets.TEST_DATABASE_INSTANCE_PASSWORD }}'
    steps:
    - uses: actions/checkout@master
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet --info
    - name: Build solution and run all tests
      run: ./build.sh
