name: Build and test
on:
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet --info
    - name: build
      run: ./build.sh
